name: shanghai scheduled Curl

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run_task:
    runs-on: ubuntu-latest

    steps:
      - name: Run curl command
        run: |
          content=$(curl -sL $URL)
          echo "$content"
          if ! [[ "$content" =~ ^[0-9]+$ ]]; then
            echo "The output may be wrong."
            exit 1
          fi
        env:
          URL: ${{ secrets.Shanghai_Happy_Url }}
