name: shanghai scheduled Curl

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # 每十分钟触发一次任务

jobs:
  run_task:
    runs-on: ubuntu-latest

    steps:
      - name: Run curl command
        run: |
          content=$(curl -s $URL)
          echo "$content"
        env:
          URL: ${{ secrets.Shanghai_Happy_Url }}
